name: Docker Image Build Test

on:
  pull_request:
    branches:
      - main
    paths:
      - container/**

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3.3.0

    - name: Build the container
      run: |
        cd container
        docker build -t codemaze/noi-linux:$GITHUB_SHA .

    - name: Test the container
      run: |
        docker run -it codemaze/noi-linux:$GITHUB_SHA /test.sh
